### PR TITLE
add cmake example

### PR DESCRIPTION
**Pull request by XxChang**
Please see README.md for details

Thanks

### CODE REVIEW

**Comment by haixuanTao** [comment]
Would it be possible to add it to the github action `ci.yml` as follows:
```yaml
      - name: "Cmake example"
        timeout-minutes: 30
        run: cargo run --example cmake-dataflow
```

**Comment by XxChang** [comment]
This example only works on Linux right now. I don't have chance to fix it on Windows and MacOS, also I'm not good at Windows and MacOS. So I only check it on Linux by adding `if: runner.os == 'Linux'` 

Sorry about that.

**Comment by haixuanTao** [comment]
Loos good to me. @phil-opp , could you have a quick look, as i don't have that much experience in CMake. Thanks!

**Review by phil-opp — APPROVED** [review]
I don't have much cmake experience either, but I think this looks all reasonable. Thanks for the contribution!

**Comment by haixuanTao** [comment]
Thanks @phil-opp , guess we´ll both learn this way :)

**Pull request merged**
