### PR TITLE
List failed and finished dataflows in `dora list`

### PR DESCRIPTION
**Pull request by phil-opp**
List failed and finished dataflows on `dora list`, in addition to the active ones. This makes it easier to find out whether a started dataflow was successful or not.

Example Output:

```
❯ dora list
No dataflows are running
Failed dataflows:
- [grateful-song] 019010f5-9235-7d67-8fbc-1e82c16a8334
Finished dataflows:
- [nasty-statement] 019010f2-cb23-7274-bc2e-f383506770a0
- [pretty-carpenter] 019010f2-e297-74fc-a765-8b80e4e1ab97
- [encouraging-cough] 019010f3-a788-748c-9196-6104d58cd9d
```

### CODE REVIEW

**Comment by haixuanTao** [comment]
Could be good to represent them within a table format instead of a list format in line with `docker ps`:

See: https://docs.docker.com/reference/cli/docker/container/ls/

We could list running dataflow first and finished dataflow at the end.

**Comment by haixuanTao** [comment]
For the tab we can probably just use this: https://github.com/BurntSushi/tabwriter

**Review by haixuanTao — APPROVED** [review]
Could be good that the naming follows kubernetes naming: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/

So:

    Running
    Succeeded
    Failed

Thanks a lot!

Otherwise looks great!

**Comment by phil-opp** [comment]
Sure, I renamed the status fields in d2e2eef9. I also refactored the message a bit in 262f39fb to make the ordering more consistent (failed and succeeded dataflows are now listed chronologically instead of in separate groups).

Feel free to merge if this looks good to you now!

**Pull request merged**
