### PR TITLE
Update zenoh to `v0.6.0-beta`

### PR DESCRIPTION
**Pull request by phil-opp**

### CODE REVIEW

**Comment by haixuanTao** [comment]
I tried to make the update but didn't check the `SessionDeclarations` trait. Thanks for updating `zenoh` and was stuck with the borrowed lifetime.

**Comment by haixuanTao** [comment]
Blocked by https://github.com/eclipse-zenoh/zenoh/issues/359 , version pinning of `zenoh` has been pushed back to `v0.2`

**Comment by phil-opp** [comment]
This is still not working, even with the latest zenoh master branch, so we decided to keep using the currently pinned version for now. I'll leave this PR open because we want to fix it eventually, but I will mark it as a draft again.

**Comment by phil-opp** [comment]
Superseded by #203.

**Pull request closed without merging**
