### PR TITLE
Add a support matrix with planned feature to clarify dora status

### PR DESCRIPTION
**Pull request by haixuanTao**
This support matrix in the README should clarify the status of dora.

Related to the following issues:
- #261 
- #258

### CODE REVIEW

**Comment by haixuanTao** [comment]
This reintroduce the test that was omitting due to `iceoryx` for Microsoft and Macos.

**Comment by haixuanTao** [comment]
### [Latency Benchmark data for Windows from the CI/CD](https://github.com/dora-rs/dora/actions/runs/4793051244/jobs/8525155886)

```
Latency:
size 0x0     : 328.505µs
size 0x8     : 254.588µs
size 0x40    : 265.919µs
size 0x200   : 291.374µs
size 0x800   : 323.756µs
size 0x1000  : 518.849µs
size 0x4000  : 520.62µs
size 0xa000  : 616.323µs
size 0x64000 : 549.683µs
size 0x3e8000: 1.156088ms
```

### [Latency Benchmark data for Macos](https://github.com/dora-rs/dora/actions/runs/4793051244/jobs/8525155794)
```
Latency:
size 0x0     : 330.412µs
size 0x8     : 298.852µs
size 0x40    : 310.321µs
size 0x200   : 370.512µs
size 0x800   : 789.392µs
size 0x1000  : 415.722µs
size 0x4000  : 367.882µs
size 0xa000  : 473.202µs
size 0x64000 : 387.112µs
size 0x3e8000: 416.922µs
```

### [To compare to Linux CI/CD](https://github.com/dora-rs/dora/actions/runs/4793051244/jobs/8525155699)

```bash
size 0x0     : 547.143µs
size 0x8     : 541.679µs
size 0x40    : 537.731µs
size 0x200   : 552.839µs
size 0x800   : 516.612µs
size 0x1000  : 237.724µs
size 0x4000  : 254.244µs
size 0xa000  : 249.698µs
size 0x64000 : 260.938µs
size 0x3e8000: 644.787µs
```


We can see that the value of latency are in the same ballpark than the one for Linux. Hence the OS-agnostic nature of dora shared memory.

> The value of the CI/CD are not very precise as they depend on the load on each machine

**Review by phil-opp — APPROVED** [review]
Looks good, thanks!

Could you clarify how this fixes #258?

**Comment by haixuanTao** [comment]
@phil-opp , I have reintroduced ci/cd test for windows in this PR, which mean that exemple should run under our defined testsuite. I agree that it's only a partial fix, and the issue might need further inspection.

**Comment by phil-opp** [comment]
Ok, thanks for clarifying! I agree that we should continue looking into #258. I updated the wording in the PR description a bit to avoid confusion.

**Pull request merged**
