### PR TITLE
Filter default log level at `warn` for `tokio::tracing`

### PR DESCRIPTION
**Pull request by haixuanTao**
Filter log starting from `WARN` instead of `ERROR`

See: https://github.com/dora-rs/dora-drives/issues/54#issuecomment-1523327892

### CODE REVIEW

**Review by phil-opp — APPROVED** [review]
Thanks!

**Comment by phil-opp** [comment]
It's weird that this PR was only merged now. I enabled auto-merge 18 hours ago and it looks like all the tests passed shortly afterwards...

**Comment by haixuanTao** [comment]
There is a connection issue in the `no_webcam.py` test, which makes the initialization fail, which makes the other operator wait forever. I'm going to open an issue on that.

**Comment by phil-opp** [comment]
Thanks!

(linking the mentioned issue here: https://github.com/dora-rs/dora/issues/271)

**Pull request merged**
