### PR TITLE
Add basic log forwarding from daemon to CLI

### PR DESCRIPTION
**Pull request by phil-opp**
Messages are forwarded by the coordinator.

Based on #552 

## Example Output

```
❯ dora start dataflow.yml --attach
01903b72-747c-72d4-a986-abbd99cccec4
WARN  rust-sink exit: node exited before initializing dora connection
WARN  rust-node exit: node exited before initializing dora connection
Dataflow 01903b72-747c-72d4-a986-abbd99cccec4 failed:

Node `rust-sink` failed: exited with code 1 with stderr output:
---------------------------------------------------------------------------------
[...]
Error: Failed to read instrs from ./path/to/instrs.json

Caused by:
No such file or directory (os error 2)
---------------------------------------------------------------------------------

Node `rust-node` failed: exited with code 1 with stderr output:
---------------------------------------------------------------------------------
[...]
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    do_stuff()
  File "main.py", line 5, in do_stuff
    raise Exception("test exception")
Exception: test exception
---------------------------------------------------------------------------------
```

The two `WARN` lines are sent immediately once they happen. The following failure summary is sent once the dataflow has finished.

## Future Work

- In a follow-up PR, we can extend this feature to allow nodes to report errors themselves. This way, we get an alternative to showing stderr output.
- We can add more log messages for additional dataflow events. For example, we could send an `INFO`-level log message when a node exits normally.
- Extend `dora logs`: Allow to subscribe to log events of running dataflows.

### CODE REVIEW

**Comment by phil-opp** [comment]
The output now looks like this:

image

The part above the `[ERROR]` marker are the dynamic log messages that appear once they happen. The part below the `[ERROR]` marker is the result of the dataflow, which is printed once the dataflow finishes. It summarizes the results and tries to print only the relevant errors.

For example, if a node fails before connecting to dora:


image

**Comment by haixuanTao** [comment]
[Screencast from 2024-06-26 15-35-18.webm](https://github.com/dora-rs/dora/assets/22787340/4d0ea077-d669-4f19-94d4-91fcb72e8258)

So I just tried and when a python error happens with a SIGSEGV error, nothing happens

**Comment by haixuanTao** [comment]
It seems to return but like a minute after the error happens.

Maybe there is some publishing config.

**Review by haixuanTao — APPROVED** [review]
Looks good!

Can we fix clippy warning before merging it to main?

**Comment by haixuanTao** [comment]
[ERROR]
failed to run dora-coordinator: Broken pipe (os error 32)

**Comment by phil-opp** [comment]
@haixuanTao I pushed some commits that should fix the error. Could you try whether this works for you?

I'll fix the clippy warnings in a minute, then this should be ready for merging.

**Comment by haixuanTao** [comment]
Looks great! Thanks Philipp :)

**Comment by haixuanTao** [comment]
After further testing, it seems that the subscriber does not report error if the error happens within the event loop of python for some reason.
[Screencast from 2024-06-27 12-22-01.webm](https://github.com/dora-rs/dora/assets/22787340/afe271bf-3567-467b-8310-d8b665d4b37e)

**Comment by haixuanTao** [comment]
And the error is not reported within the error message summary.

**Comment by phil-opp** [comment]
Strange, it seems like the node keeps running for some reason, so it never exits with an error exit code. Instead, we have to kill it after some time because it doesn't react anymore.

**Comment by haixuanTao** [comment]
Also, after investigation of the error message it would be better to have error per node printed only once and not reprinted in the summary as it might take too much space in the terminal.

example:

```bash
```01905771-c7b8-73c3-8b24-50692e5dfc36
attaching to dataflow (use `--detach` to run in background)
ERROR lcr_leader: exited with code 1 with stderr output:
---------------------------------------------------------------------------------
[...]Traceback (most recent call last):
  File "\\?\C:\Users\accou\Desktop\dora-koch\node_hub\dynamixel_client\client.py", line 91, in <module>
    main()
  File "\\?\C:\Users\accou\Desktop\dora-koch\node_hub\dynamixel_client\client.py", line 44, in main
    chain = DynamixelXLMotorsChain(path, ids)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\?\C:\Users\accou\Desktop\dora-koch\node_hub\dynamixel_client\dynamixel.py", line 87, in __init__
    raise OSError(f"Failed to set packet timeout to {TIMOUT_MS} (ms)")
OSError: Failed to set packet timeout to 1000 (ms)
---------------------------------------------------------------------------------

WARN  lcr_leader: node exited before initializing dora connection
ERROR lcr_follower: exited with code 1 with stderr output:
---------------------------------------------------------------------------------
[...]Traceback (most recent call last):
  File "\\?\C:\Users\accou\Desktop\dora-koch\node_hub\dynamixel_client\client.py", line 91, in <module>
    main()
  File "\\?\C:\Users\accou\Desktop\dora-koch\node_hub\dynamixel_client\client.py", line 44, in main
    chain = DynamixelXLMotorsChain(path, ids)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\?\C:\Users\accou\Desktop\dora-koch\node_hub\dynamixel_client\dynamixel.py", line 87, in __init__
    raise OSError(f"Failed to set packet timeout to {TIMOUT_MS} (ms)")
OSError: Failed to set packet timeout to 1000 (ms)
---------------------------------------------------------------------------------

WARN  lcr_follower: node exited before initializing dora connection
ERROR lcr_init_leader: exited with code 1. This error occurred because node `lcr_leader` exited before connecting to dora.
ERROR lcr_init_follower: exited with code 1. This error occurred because node `lcr_leader` exited before connecting to dora.


[ERROR]
Dataflow 01905771-c7b8-73c3-8b24-50692e5dfc36 failed:

Node `lcr_leader` failed: exited with code 1 with stderr output:
---------------------------------------------------------------------------------
[...]Traceback (most recent call last):
  File "\\?\C:\Users\accou\Desktop\dora-koch\node_hub\dynamixel_client\client.py", line 91, in <module>
    main()
  File "\\?\C:\Users\accou\Desktop\dora-koch\node_hub\dynamixel_client\client.py", line 44, in main
    chain = DynamixelXLMotorsChain(path, ids)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\?\C:\Users\accou\Desktop\dora-koch\node_hub\dynamixel_client\dynamixel.py", line 87, in __init__
    raise OSError(f"Failed to set packet timeout to {TIMOUT_MS} (ms)")
OSError: Failed to set packet timeout to 1000 (ms)
---------------------------------------------------------------------------------

Node `lcr_follower` failed: exited with code 1 with stderr output:
---------------------------------------------------------------------------------
[...]Traceback (most recent call last):
  File "\\?\C:\Users\accou\Desktop\dora-koch\node_hub\dynamixel_client\client.py", line 91, in <module>
    main()
  File "\\?\C:\Users\accou\Desktop\dora-koch\node_hub\dynamixel_client\client.py", line 44, in main
    chain = DynamixelXLMotorsChain(path, ids)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\?\C:\Users\accou\Desktop\dora-koch\node_hub\dynamixel_client\dynamixel.py", line 87, in __init__
    raise OSError(f"Failed to set packet timeout to {TIMOUT_MS} (ms)")
OSError: Failed to set packet timeout to 1000 (ms)
---------------------------------------------------------------------------------
``````

**Comment by haixuanTao** [comment]
Yes it could be a python error

**Comment by haixuanTao** [comment]
[Screencast from 2024-06-27 14-02-01.webm](https://github.com/dora-rs/dora/assets/22787340/bf5f2ac5-b599-4c1e-a6a3-e23b0c000256)

The error seems to be reported in the logs though but not in the terminal

**Comment by haixuanTao** [comment]
Sorry seems to be linked to the unbind dict from #557 . If i delete the event the error disappear.
[Screencast from 2024-06-27 14-33-21.webm](https://github.com/dora-rs/dora/assets/22787340/f7bac75e-c56d-4051-ab47-8c91f3cc75d6)

**Comment by haixuanTao** [comment]
So, I opened https://github.com/dora-rs/dora/pull/568 as their is a GIL Lock Race Condition between drop token that are not able to report they are drop and the Node not stopping to let the drop token free itself.

**Comment by haixuanTao** [comment]
> Also, after investigation of the error message it would be better to have error per node printed only once and not reprinted in the summary as it might take too much space in the terminal.
> 
> example:
> 
> ```shell
> ```01905771-c7b8-73c3-8b24-50692e5dfc36
> attaching to dataflow (use `--detach` to run in background)
> ERROR lcr_leader: exited with code 1 with stderr output:
> ---------------------------------------------------------------------------------
> [...]Traceback (most recent call last):
>   File "\\?\C:\Users\accou\Desktop\dora-koch\node_hub\dynamixel_client\client.py", line 91, in <module>
>     main()
>   File "\\?\C:\Users\accou\Desktop\dora-koch\node_hub\dynamixel_client\client.py", line 44, in main
>     chain = DynamixelXLMotorsChain(path, ids)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "\\?\C:\Users\accou\Desktop\dora-koch\node_hub\dynamixel_client\dynamixel.py", line 87, in __init__
>     raise OSError(f"Failed to set packet timeout to {TIMOUT_MS} (ms)")
> OSError: Failed to set packet timeout to 1000 (ms)
> ---------------------------------------------------------------------------------
> 
> WARN  lcr_leader: node exited before initializing dora connection
> ERROR lcr_follower: exited with code 1 with stderr output:
> ---------------------------------------------------------------------------------
> [...]Traceback (most recent call last):
>   File "\\?\C:\Users\accou\Desktop\dora-koch\node_hub\dynamixel_client\client.py", line 91, in <module>
>     main()
>   File "\\?\C:\Users\accou\Desktop\dora-koch\node_hub\dynamixel_client\client.py", line 44, in main
>     chain = DynamixelXLMotorsChain(path, ids)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "\\?\C:\Users\accou\Desktop\dora-koch\node_hub\dynamixel_client\dynamixel.py", line 87, in __init__
>     raise OSError(f"Failed to set packet timeout to {TIMOUT_MS} (ms)")
> OSError: Failed to set packet timeout to 1000 (ms)
> ---------------------------------------------------------------------------------
> 
> WARN  lcr_follower: node exited before initializing dora connection
> ERROR lcr_init_leader: exited with code 1. This error occurred because node `lcr_leader` exited before connecting to dora.
> ERROR lcr_init_follower: exited with code 1. This error occurred because node `lcr_leader` exited before connecting to dora.
> 
> 
> [ERROR]
> Dataflow 01905771-c7b8-73c3-8b24-50692e5dfc36 failed:
> 
> Node `lcr_leader` failed: exited with code 1 with stderr output:
> ---------------------------------------------------------------------------------
> [...]Traceback (most recent call last):
>   File "\\?\C:\Users\accou\Desktop\dora-koch\node_hub\dynamixel_client\client.py", line 91, in <module>
>     main()
>   File "\\?\C:\Users\accou\Desktop\dora-koch\node_hub\dynamixel_client\client.py", line 44, in main
>     chain = DynamixelXLMotorsChain(path, ids)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "\\?\C:\Users\accou\Desktop\dora-koch\node_hub\dynamixel_client\dynamixel.py", line 87, in __init__
>     raise OSError(f"Failed to set packet timeout to {TIMOUT_MS} (ms)")
> OSError: Failed to set packet timeout to 1000 (ms)
> ---------------------------------------------------------------------------------
> 
> Node `lcr_follower` failed: exited with code 1 with stderr output:
> ---------------------------------------------------------------------------------
> [...]Traceback (most recent call last):
>   File "\\?\C:\Users\accou\Desktop\dora-koch\node_hub\dynamixel_client\client.py", line 91, in <module>
>     main()
>   File "\\?\C:\Users\accou\Desktop\dora-koch\node_hub\dynamixel_client\client.py", line 44, in main
>     chain = DynamixelXLMotorsChain(path, ids)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "\\?\C:\Users\accou\Desktop\dora-koch\node_hub\dynamixel_client\dynamixel.py", line 87, in __init__
>     raise OSError(f"Failed to set packet timeout to {TIMOUT_MS} (ms)")
> OSError: Failed to set packet timeout to 1000 (ms)
> ---------------------------------------------------------------------------------
> ```
> 
> @Hennzau

So I tried to remove the double reporting of errors in the logs, but it seems that if an error happens after a stop message.

The error message only get printed by the dataflow failed summary and not within the loop.
Screencast from 2024-06-28 12-18-03.webm

**Comment by phil-opp** [comment]
Regarding the double reporting: I think it's worth it to keep the error summary at the end, even if the errors were already reported previously. For example, image that we add more log events in the future. Then the first error might be difficult to find so that users might focus on the wrong error.

How about we shorten the summary and only show the single error that occured first? We could add a message like "X more errors occurred (see above)".

**Comment by phil-opp** [comment]
> The error message only get printed by the dataflow failed summary and not within the loop.
> [Screencast from 2024-06-28 12-18-03.webm](https://github.com/dora-rs/dora/assets/22787340/5838b379-edd7-4ce0-b99a-ca901168c063)

This could be a race between the two requests (log subscribe and result query). As soon as the result is available, the CLI closes the log subscription stream, so that the last error log message might be ignored. (Not sure if that is the reason here, just a possibility.)

**Comment by haixuanTao** [comment]
> Regarding the double reporting: I think it's worth it to keep the error summary at the end, even if the errors were already reported previously. For example, image that we add more log events in the future. Then the first error might be difficult to find so that users might focus on the wrong error.
> 
> How about we shorten the summary and only show the single error that occured first? We could add a message like "X more errors occurred (see above)".

It seems to me that having error reporting in their order of occurrence a simpler way to debug than just checking a summary that may or may not respect order of occurrence. 

I don't think that we should show a single error. As we can see above the error could be reported in multiple file using the same logic.

**Comment by haixuanTao** [comment]
> > The error message only get printed by the dataflow failed summary and not within the loop.
> > [Screencast from 2024-06-28 12-18-03.webm](https://github.com/dora-rs/dora/assets/22787340/5838b379-edd7-4ce0-b99a-ca901168c063)
> 
> This could be a race between the two requests (log subscribe and result query). As soon as the result is available, the CLI closes the log subscription stream, so that the last error log message might be ignored. (Not sure if that is the reason here, just a possibility.)

Could be good to have a fix on this.

I am ok to keep the summary for now as we will need it to have all error reported but it seems like we need to make sure that all error are reported within the log message.

But, I still doubt the effectiveness of the Summary as it takes a lot of **terminal spaces** without adding more info as previously reported if not showing less information without any info. warn traces within its timeline and makes it harder to check the actual error in its context.

Moreover, we can clearly see that we can have quirky behaviour such as race condition between the summary and the actual error reporting, making the whole logic of Log Subscription a bit complex. I have for example trouble figuring out the race condition, and so, maybe we should just keep a simple subscription design.

**Comment by phil-opp** [comment]
The original motivation for the summary was that errors can lead to other errors in many cases. For example, when one node fails/exits before connecting to dora, the dora initialization fails on all other nodes. In the summary, we filter these cascading errors out, so it becomes easier to find the error that caused it all. Without the summary, you might have to scroll up very far and ignore all the cascading errors that occured later.

I think the best course of action is the following:

- Ensure that the all errors are printed as part of the subscription.
- Don't print a summary if there is only one error.
- If there are multiple errors, print a summary that repeats the first non-cascading error. The message could then be something like:
  ```
  [ERROR]
  Dataflow 01905771-c7b8-73c3-8b24-50692e5dfc36 failed because X errors occured. The first error was:
  
  Node `lcr_leader` failed: exited with code 1 with stderr output:
  ---------------------------------------------------------------------------------
  [...]Traceback (most recent call last):
    File "\\?\C:\Users\accou\Desktop\dora-koch\node_hub\dynamixel_client\client.py", line 91, in <module>
      main()
  ```

This way, we reduce repetition, but still make it easy to find the first error without scrolling. What do you think, @haixuanTao ?

**Pull request merged**
