### PR TITLE
Create dataflow html file in current directory

### PR DESCRIPTION
**Pull request by phil-opp**
Chrome does not permit opening HTML files from the tmp directory.

### CODE REVIEW

**Comment by phil-opp** [comment]
@heyong4725 Could you check whether it work for you now? You can also pass an `--open` flag to open the file directly in the default browser.

**Comment by heyong4725** [comment]
I verified this fix works!

**Comment by heyong4725** [comment]
It works! @phil-opp

**Review by haixuanTao — APPROVED** [review]

**Review by heyong4725 — APPROVED** [review]

**Comment by phil-opp** [comment]
Great, thanks for testing!

**Pull request merged**
