### PR TITLE
Redesign communication layer to be synchronous and add support for iceoryx

### LINKED ISSUE #75: Use shared memory for inter-node communication
This should considerably improve performance for large messages, compared to `zenoh`.

- [x] Add support for [`iceoryx`](https://github.com/eclipse-iceoryx) as an alternative to `zenoh`

### PR DESCRIPTION
**Pull request by phil-opp**
This PR completly rewrites the communication layer to be synchronous instead of asynchronous. The new design was chosen so that both `zenoh` and `iceoryx` can be supported without issues. 

Similar to the operator API and the other node APIs, the Rust node API is now completely synchronous too.

Fixes #75

### CODE REVIEW

**Comment by haixuanTao** [comment]
So I runned both `iceoryx` demo and the `python-dataflow` example and replacing the `yaml` config. And it seems to work. I think that it would be beneficial to have a bit of documentation on running `RouDi`, which is only in the CI at the moment.

**Comment by phil-opp** [comment]
Thanks for testing!

> I think that it would be beneficial to have a bit of documentation on running `RouDi`, which is only in the CI at the moment.

Good point! I'll add more docs for that.

**Review by haixuanTao — APPROVED** [review]
I also tested `iceoryx` on `dora-drives` and it seems to work. 

Thanks for the PR :) 

I sometimes get: `thread '<unnamed>' panicked at 'stop stream was disconnected unexpectedly', apis/rust/node/src/communication/mod.rs:163:43` , don't know if it is my system or a problem with the messaging system but seems to work most of the time.

I will update `dora-drives` once this is merged.

**Comment by phil-opp** [comment]
> I sometimes get: `thread '<unnamed>' panicked at 'stop stream was disconnected unexpectedly', apis/rust/node/src/communication/mod.rs:163:43` , don't know if it is my system or a problem with the messaging system but seems to work most of the time.

Thanks for reporting! I pushed another commit that should fix this problem.

**Pull request merged**
