### PR TITLE
Release v0.3.0

### PR DESCRIPTION
**Pull request by haixuanTao**

### CODE REVIEW

**Review by phil-opp — APPROVED** [review]
Thanks! Maybe we could reorder the changelog for v0.3 a bit to list the larger/breaking PRs first?

**Comment by haixuanTao** [comment]
Sure. I have replaced a fixed cache alignement with the constant aligned_vec cache alignment that is based on architecture. 
```rust

// https://rust-lang.github.io/hashbrown/src/crossbeam_utils/cache_padded.rs.html#128-130
pub const CACHELINE_ALIGN: usize = {
    #[cfg(any(
        target_arch = "x86_64",
        target_arch = "aarch64",
        target_arch = "powerpc64",
    ))]
    {
        128
    }
    #[cfg(any(
        target_arch = "arm",
        target_arch = "mips",
        target_arch = "mips64",
        target_arch = "riscv64",
    ))]
    {
        32
    }
    #[cfg(target_arch = "s390x")]
    {
        256
    }
    #[cfg(not(any(
        target_arch = "x86_64",
        target_arch = "aarch64",
        target_arch = "powerpc64",
        target_arch = "arm",
        target_arch = "mips",
        target_arch = "mips64",
        target_arch = "riscv64",
        target_arch = "s390x",
    )))]
    {
        64
    }
};

```

Normally, this should be cross-architecture compatible as we are sending it as a slice.

**Comment by phil-opp** [comment]
The alignment is not about cache lines here, it's about the alignment required by arrow types. So instead of making it platform dependent, we should replace the `avec` macro invocation with the `AVec::new` constructor.

(I missed that `avec` creates cache-line aligned vectors. It just coincidentally matched the required alignment on the platform. I was building on.)

**Comment by haixuanTao** [comment]
Ok make sense. Thanks. Will do the change.

**Pull request merged**
