### PR TITLE
Autogenerate a name for started dataflows if none is given

### LINKED ISSUE #266: Dataflow with no specified name shows unnamed
**Is your feature request related to a problem? Please describe.**
Dataflow with no specified name shows unnamed, as follows:
image
```
impl Display for DataflowId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        if let Some(name) = &self.name {
            write!(f, "[{name}] {}", self.uuid)
        } else {
            write!(f, "[<unnamed>] {}", self.uuid)
        }
    }
}
```

**Describe the solution you'd like**
Is it possible for dataflow without a name to randomly generate a unique name for it.

### PR DESCRIPTION
**Pull request by phil-opp**
Generates random `adjective-noun` names such as `faded-eye` or `grubby-bath`.

Fixes #266

### CODE REVIEW

**Comment by haixuanTao** [comment]
@meua  can you try to see if that correspond to what you expect if you have time? https://github.com/dora-rs/dora/issues/266

**Comment by meua** [comment]
Relying on the conda virtual environment, how can I debug both python and rust programs in the clion or vscode editor. I'm finding it difficult to debug a rust program and python at the same time, do you guys have any good suggestions.

**Comment by haixuanTao** [comment]
We actually don't depend on conda directly. (pyo3 does)

You should try to:
```bash
# Without conda activated
cd apis/python/node
maturin build --release
cd ../../..
pip install target/wheels/*
```

And try again.

Normally you should be able to run your current clion program

**Comment by meua** [comment]
> We actually don't depend on conda directly. (pyo3 does)
> 
> You should try to:
> 
> ```shell
> # Without conda activated
> cd apis/python/node
> maturin build --release
> cd ../../..
> pip install target/wheels/*
> ```
> 
> And try again.
> 
> Normally you should be able to run your current clion program

Thanks a lot, I tried to do it like this.

**Comment by meua** [comment]
> We actually don't depend on conda directly. (pyo3 does)
> 
> You should try to:
> 
> ```shell
> # Without conda activated
> cd apis/python/node
> maturin build --release
> cd ../../..
> pip install target/wheels/*
> ```
> 
> And try again.
> 
> Normally you should be able to run your current clion program

Thanks, `dora-cli start /path/to/dataflow.yaml` depend on conda virtual envs, so cause the exception above. I don’t know how to configure clion, and configure python’s conda virtual environment before running it.
image

After outputting uuid through terminal execution, dataflow will exit immediately, and I have no chance to run dora-cli list to view the randomly generated alias of dataflow.
```bash
(dora3.7) jarvis@jia:~/coding/rust_home/github.com/meua/dora/binaries/cli/src$ cargo run start ../../../examples/python-operator-dataflow/dataflow.yml --attach --hot-reload 
   Compiling futures-util v0.3.25
   Compiling tokio v1.26.0
   ...
   Compiling bat v0.23.0
   Compiling dora-tracing v0.2.2 (/home/jarvis/coding/rust_home/github.com/meua/dora/libraries/extensions/telemetry/tracing)
   Compiling dora-node-api v0.2.2 (/home/jarvis/coding/rust_home/github.com/meua/dora/apis/rust/node)
   Compiling dora-node-api-c v0.2.2 (/home/jarvis/coding/rust_home/github.com/meua/dora/apis/c/node)
   Compiling dora-cli v0.2.2 (/home/jarvis/coding/rust_home/github.com/meua/dora/binaries/cli)
    Finished dev [unoptimized + debuginfo] target(s) in 16.38s
     Running `/home/jarvis/coding/rust_home/github.com/meua/dora/target/debug/dora-cli start ../../../examples/python-operator-dataflow/dataflow.yml --attach --hot-reload`
a2045c17-1818-4f30-9778-372f28a56f8d
(dora3.7) jarvis@jia:~/coding/rust_home/github.com/meua/dora/binaries/cli/src$ 
```

**Comment by meua** [comment]
> Generates random `adjective-noun` names such as `faded-eye` or `grubby-bath`.
> 
> Fixes #266
Thank you @phil-opp , the alias is working fine.
image

**Pull request merged**
