### PR TITLE
Allocate shared memory in nodes to improve throughput

### PR DESCRIPTION
**Pull request by phil-opp**
This commit migrates the allocation of shared memory samples from the daemon to the individual nodes. This way, the nodes can prepare the memory themselves when sending outputs. Thus, we avoid the extra roundtrip to the daemon that we used before (the prepare request and reply). The other advantage is that we can now queue shared memory outputs on the TCP socket without waiting for replies from the daemon (like we already do for `Vec`-backed messages).

Since the senders themselves remain the owners of the shared memory regions now, we need to forwards the drop tokens to the corresponding sending nodes. These drop events are handled internally by the node API. They are passed through a new channel from the event handler thread to the `DoraNode` instance, which can then free or reuse the dropped regions on the next `send_output`. To ensure that we don't clean up a shared memory region too early, we wait for the pending drop tokens in `DoraNode`'s `Drop` implementation. The waiting is done with a timeout to ensure that we don't deadlock when a token is lost for some reason.

### CODE REVIEW

**Review by haixuanTao — APPROVED** [review]
Nice!

**Comment by phil-opp** [comment]
Should we do the new release first before we merge this?

**Comment by haixuanTao** [comment]
So, I tested this PR extensively and it does not seem to be breaking. I think we can merge it before the next release.

**Comment by phil-opp** [comment]
Ok great, then let's merge this. Thanks for testing!

**Pull request merged**
