### PR TITLE
Create a staticlib with a node API for C

### PR DESCRIPTION
**Pull request by phil-opp**
Enables the creation of custom nodes in C.

TODO:

- [x] Testing
- [x] Usage example
- [x] README

### CODE REVIEW

**Comment by haixuanTao** [comment]
On the `c-dataflow/run.rs`. Is this script, just for the CI and ease of testing it out, or would you recommend users to use a similar pattern run script to launch the dataflow?
From a user perspective, compiling c from rust might not be common knowledge I feel. And, therefore I would maybe just write a few lines in the `README.md` on how to run the dataflow without the run script.

**Comment by phil-opp** [comment]
The `run.rs` script is just for easier testing, since there are quite a number of steps. I assume that most C projects have their own build system, so I expect that most people will just integrate the build steps there.



> From a user perspective, compiling c from rust might not be common knowledge I feel. And, therefore I would maybe just write a few lines in the `README.md` on how to run the dataflow without the run script.

Yeah, agreed! I will write up some instructions.

**Review by haixuanTao — APPROVED** [review]
So I ran the `c-dataflow` on my computer and did not have any issue.
Just for info, I have a couple of zenoh log when I run on `stdout`, and i feel that it should not be default, but it's not directly linked to this PR.

**Comment by phil-opp** [comment]
Thanks for testing!



> Just for info, I have a couple of zenoh log when I run on `stdout`, and i feel that it should not be default, but it's not directly linked to this PR.

Yeah, I get these too. I'll open a follow-up PR to hide the low-priority messages (e.g. debug level), but I'm not sure if we should also hide WARN log messages...

**Pull request merged**
