### PR TITLE
Improve coordinator port config

### PR DESCRIPTION
**Pull request by phil-opp**
- Allow setting custom control port in coordinator
- Set default in CLI parsing -> default shown in `--help` output
- Add support for custom coordinator control port numbers in CLI

Follow-up to #513

### CODE REVIEW

**Comment by Gege-Wang** [comment]
Now, we can do this.
- To make coordinator_control_port configurable.
```
# remote
ubuntu@ip-172-31-30-172:~/dora$ dora coordinator --port 6014 --control-interface 0.0.0.0 --control-port 6013
Listening for incoming daemon connection on 6014

# local
$ ./target/release/dora check --coordinator-addr 54.234.111.197 --coordinator-port 6013
Dora Coordinator: ok
Dora Daemon: not running
```
- Daemon connect to remote coordinator
```
# remote
ubuntu@ip-172-31-30-172:~/dora$ dora coordinator
Listening for incoming daemon connection on 53290

# local
$ ./target/release/dora daemon --coordinator-addr 54.234.111.197:53290

$ ./target/release/dora check --coordinator-addr 54.234.111.197           1 ↵
Dora Coordinator: ok
Dora Daemon: ok
```

**Comment by Gege-Wang** [comment]
What does it do when we use `dora up --coordinator-addr`? 
When coordinator and daemon are running in remote machine, ` dora up --coordinator-addr <remote-ip>`  in local machine doesn't seem to do anything. 
When only a coordinator is running in remote machine, the local dora up --coordinator-addr <remote-ip> does not seem to be able to start the connection between daemon and coordinator.
```
# remote 
ubuntu@ip-172-31-30-172:~$ dora coordinator
Listening for incoming daemon connection on 53290

# local
$ ./target/release/dora up --coordinator-addr 54.234.111.197              2 ↵
started dora daemon
daemon not connected after 2.1000001s
```
Did I misunderstand anything?

**Comment by XxChang** [comment]
> What does it do when we use `dora up --coordinator-addr`? When coordinator and daemon are running in remote machine, ` dora up --coordinator-addr <remote-ip>` in local machine doesn't seem to do anything. When only a coordinator is running in remote machine, the local dora up --coordinator-addr does not seem to be able to start the connection between daemon and coordinator.
> 
> ```
> # remote 
> ubuntu@ip-172-31-30-172:~$ dora coordinator
> Listening for incoming daemon connection on 53290
> 
> # local
> $ ./target/release/dora up --coordinator-addr 54.234.111.197              2 ↵
> started dora daemon
> daemon not connected after 2.1000001s
> ```
> 
> Did I misunderstand anything?

It seems like that `start_daemon()` use default command which is `dora daemon`, daemon connect to local coordinator which was launched by `dora up`

**Comment by XxChang** [comment]
In addition, we should replace

`cmd.spawn()`

by

```
    if !cmd.status().wrap_err("failed to run `dora daemon`")?.success() {
        eyre::bail!("failed to start dora daemon");
    }
```

to capture cli error

**Comment by phil-opp** [comment]
Thanks for testing!

> What does it do when we use `dora up --coordinator-addr`?

The `coordinator-addr` is currently only used for checking the connection after starting. So this doesn't really work (yet?).

For now, it's probably best to remove the `coordinator-addr` argument from `dora up` and instruct users to use the manual spawn commands for remote deployments. The commands `dora coordinator` for running the coordinator and `dora daemon` for running the daemon.

**Comment by phil-opp** [comment]
> In addition, we should replace
> 
> `cmd.spawn()`
> 
> by
> 
> ```
>     if !cmd.status().wrap_err("failed to run `dora daemon`")?.success() {
>         eyre::bail!("failed to start dora daemon");
>     }
> ```
> 
> to capture cli error

This would wait until the daemon exits, which we don't want to do here (we want to spawn it in the background).

**Comment by XxChang** [comment]
> > In addition, we should replace
> 
> > 
> 
> > `cmd.spawn()`
> 
> > 
> 
> > by
> 
> > 
> 
> > ```
> 
> >     if !cmd.status().wrap_err("failed to run `dora daemon`")?.success() {
> 
> >         eyre::bail!("failed to start dora daemon");
> 
> >     }
> 
> > ```
> 
> > 
> 
> > to capture cli error
> 
> 
> 
> This would wait until the daemon exits, which we don't want to do here (we want to spawn it in the background).

Copy that, i read it wrong, sorry

**Review by haixuanTao — APPROVED** [review]
Looks great thanks!

**Pull request merged**
