### PR TITLE
Use typed inputs in Python ROS2 example

### PR DESCRIPTION
**Pull request by phil-opp**
Based on #343

### CODE REVIEW

**Comment by phil-opp** [comment]
It looks like the `pa.array` function converts a Python dict to an array of strings.

For example, the following dict becomes `["linear", "angular"]` after conversion:

```python
direction = {
    "linear": {
        "x": event["value"][0],
    },
    "angular": {
        "z": event["value"][5],
    },
}
```

@haixuanTao Do you have an idea how we can fix this? I tried supplying an explicit type by passing a `type` argument to the `pa.array` call, but this doesn't seem to work for dicts that have Python strings as keys...

**Comment by haixuanTao** [comment]
Yes indeed, I think that we should use: `pa.array([py_dict])`, I'm checking as well the example

**Comment by haixuanTao** [comment]
Actually, we should use `pa.scalar(direction)`  to return a Struct type.

**Comment by phil-opp** [comment]
Thanks for investigating! I can confirm that `pa.scalar` does the dict->struct conversion properly. We still need to wrap it into a `pa.array` afterwards though because the [`FromPyArrow`](https://docs.rs/arrow/46.0.0/arrow/pyarrow/trait.FromPyArrow.html) is not implemented for the `pyarrow.StructScalar` type.

**Comment by phil-opp** [comment]
> We still need to wrap it into a `pa.array` afterwards though because the [`FromPyArrow`](https://docs.rs/arrow/46.0.0/arrow/pyarrow/trait.FromPyArrow.html) is not implemented for the `pyarrow.StructScalar` type.

I just pushed 7f90c13 to do this conversion automatically inside the `publish` implementation.

**Comment by phil-opp** [comment]
Looks like we can even get a step further and convert Python dicts automatically (implemented in 2a19044).

I only applied this to ROS2 publish operations right now, not to dora `send_output` calls. I don't think that it's a good idea to perform such automated conversions for dora outputs right now because the inputs/outputs are still dynamically typed (so automated type adjustments could be confusing). We can add the conversions as soon as we have a proper way to explicitly specify the types for inputs and outputs in the dataflow file.

**Review by haixuanTao — APPROVED** [review]

**Pull request merged**
